/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LableImage: typeof import('./src/components/lableImage.vue')['default']
    List: typeof import('./src/components/list.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
  }
}
