name: suto-build
on: 
  push:
    branches: [main]
    paths-ignore:
      - README.md
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: chekout
        uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: npm install i
      - run: npm run build
